# -*- coding: utf-8 -*-
"""hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9jwhM4SmUm8GC7ThvZsVhZhnsKfotBr
"""

def say_hello(name: str, repeat: int = 1, goodbye: bool = False) -> None:

  if goodbye:
      message = 'Goodbye'
  else:
      message = 'Hello'

  for _ in range(repeat):
      print(f'{message} {name}!')



say_hello('World')
say_hello('World', 3, True)